name = "Applications Setup"

[[data]]
name = "Communication Apps"

[[data.entries]]
name = "Discord"
description = "Discord is a versatile communication platform for gamers and communities, offering voice, video, and text chat features."
script = "communication-apps/discord-setup.sh"

[[data.entries]]
name = "Signal"
description = "Signal is a privacy-focused messaging app that provides end-to-end encryption for secure text, voice, and video communication."
script = "communication-apps/signal-setup.sh"

[[data.entries]]
name = "Slack"
description = "Slack is a collaboration platform designed for team communication, featuring channels, direct messaging, file sharing, and integrations with various productivity tools."
script = "communication-apps/slack-setup.sh"

[[data.entries]]
name = "Telegram"
description = "Telegram is a cloud-based messaging app known for its speed and security, offering features like group chats, channels, and end-to-end encrypted calls."
script = "communication-apps/telegram-setup.sh"

[[data.entries]]
name = "Thunderbird"
description = "Thunderbird is a free, open-source email client that offers powerful features like customizable email management, a built-in calendar, and extensive add-ons for enhanced functionality."
script = "communication-apps/thunderbird-setup.sh"

[[data.entries]]
name = "WhatsApp"
description = "WhatsApp is a popular messaging application that allows users to send text messages, voice messages, make voice and video calls, and share media files."
script = "communication-apps/whatsapp-setup.sh"

[[data]]
name = "Developer Tools"

[[data.entries]]
name = "Github Desktop"
description = "GitHub Desktop is a user-friendly application that simplifies the process of managing Git repositories and interacting with GitHub, providing a graphical interface for tasks like committing, branching, and syncing changes."
script = "developer-tools/githubdesktop.sh"

[[data.entries]]
name = "JetBrains Toolbox"
description = "JetBrains Toolbox is a collection of tools and an app that help developers work with JetBrains products."
script = "developer-tools/jetbrains-toolbox.sh"

[[data.entries]]
name = "Neovim"
description = "Neovim is a refactor, and sometimes redactor, in the tradition of Vim.\nIt is not a rewrite but a continuation and extension of Vim.\nThis command configures neovim from CTT's neovim configuration.\nhttps://github.com/ChrisTitusTech/neovim"
script = "developer-tools/neovim.sh"

[[data.entries]]
name = "Sublime Text"
description = "Sublime Text is a fast, lightweight, and customizable text editor known for its simplicity, powerful features, and wide range of plugins for various programming languages."
script = "developer-tools/sublime.sh"

[[data.entries]]
name = "VS Code"
description = "Visual Studio Code (VS Code) is a lightweight, open-source code editor with built-in support for debugging, version control, and extensions for various programming languages and frameworks."
script = "developer-tools/vscode.sh"

[[data.entries]]
name = "VS Codium"
description = "VSCodium is a free, open-source version of Visual Studio Code (VS Code) that removes Microsoft-specific telemetry and branding."
script = "developer-tools/vscodium.sh"

[[data.entries]]
name = "Zed"
description = "Zed is a next-generation code editor written in rust, designed for high-performance collaboration with humans and AI."
script = "developer-tools/zed.sh"

[[data]]
name = "Web Browsers"

[[data.entries]]
name = "Brave"
description = "Brave is a free and open-source web browser developed by Brave Software, Inc. based on the Chromium web browser."
script = "browsers/brave.sh"

[[data.entries]]
name = "Chromium"
description = "Chromium is an open-source web browser project started by Google, to provide the source code for the proprietary Google Chrome browser."
script = "browsers/chromium.sh"

[[data.entries]]
name = "Google Chrome"
description = "Google Chrome is a fast, secure, and free web browser, built for the modern web."
script = "browsers/google-chrome.sh"

[[data.entries]]
name = "LibreWolf"
description = "LibreWolf is a fork of Firefox, focused on privacy, security, and freedom."
script = "browsers/librewolf.sh"

[[data.entries]]
name = "Mozilla Firefox"
description = "Mozilla Firefox is a free and open-source web browser developed by the Mozilla Foundation."
script = "browsers/firefox.sh"

[[data.entries]]
name = "Zen Browser"
description = "Zen Browser is a privacy-focused web browser designed for enhanced security and a seamless browsing experience."
script = "browsers/zen-browser.sh"

[[data.entries]]
name = "Thorium"
description = "Thorium is a Chromium-based browser focused on privacy and performance."
script = "browsers/thorium.sh"

[[data.entries]]
name = "Vivaldi"
description = "Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies."
script = "browsers/vivaldi.sh"

[[data.entries]]
name = "waterfox"
description = "Waterfox is the privacy-focused web browser engineered to give you speed, control, and peace of mind on the internet."
script = "browsers/waterfox.sh"

[[data]]
name = "Alacritty"
description = "Alacritty is a modern terminal emulator that comes with sensible defaults, but allows for extensive configuration. By integrating with other applications, rather than reimplementing their functionality, it manages to provide a flexible set of features with high performance. The supported platforms currently consist of BSD, Linux, macOS and Windows. This command installs and configures alacritty terminal emulator."
script = "alacritty-setup.sh"

[[data]]
name = "Android Debloater"
description = "Universal Android Debloater (UAD) is a tool designed to help users remove bloatware and unnecessary pre-installed applications from Android devices, enhancing performance and user experience."
script = "android-debloat.sh"

[[data]]
name = "Fastfetch"
description = "Fastfetch is a neofetch-like tool for fetching system information and displaying it prettily. It is written mainly in C, with performance and customizability in mind. This command installs fastfetch and configures from CTT's mybash repository. https://github.com/ChrisTitusTech/mybash"
script = "fastfetch-setup.sh"

[[data]]
name = "Kitty"
description = "kitty is a free and open-source GPU-accelerated terminal emulator for Linux, macOS, and some BSD distributions, focused on performance and features. kitty is written in a mix of C and Python programming languages. This command installs and configures kitty."
script = "kitty-setup.sh"

[[data]]
name = "ZSH Prompt"
description = "The Z shell is a Unix shell that can be used as an interactive login shell and as a command interpreter for shell scripting. Zsh is an extended Bourne shell with many improvements, including some features of Bash, ksh, and tcsh. This command installs ZSH prompt and provides basic configuration."
script = "zsh-setup.sh"
